In [2]:
pip install pandas numpy matplotlib seaborn scikit-learn xgboost ucimlrepo


Load dataset

In [3]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
diabetes_130_us_hospitals_for_years_1999_2008 = fetch_ucirepo(id=296)

# data (as pandas dataframes)
X = diabetes_130_us_hospitals_for_years_1999_2008.data.features
y = diabetes_130_us_hospitals_for_years_1999_2008.data.targets

# metadata
print(diabetes_130_us_hospitals_for_years_1999_2008.metadata)

# variable information
print(diabetes_130_us_hospitals_for_years_1999_2008.variables)


/usr/local/lib/python3.12/dist-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)


{'uci_id': 296, 'name': 'Diabetes 130-US Hospitals for Years 1999-2008', 'repository_url': 'https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008', 'data_url': 'https://archive.ics.uci.edu/static/public/296/data.csv', 'abstract': 'The dataset represents ten years (1999-2008) of clinical care at 130 US hospitals and integrated delivery networks. Each row concerns hospital records of patients diagnosed with diabetes, who underwent laboratory, medications, and stayed up to 14 days. The goal is to determine the early readmission of the patient within 30 days of discharge.\nThe problem is important for the following reasons. Despite high-quality evidence showing improved clinical outcomes for diabetic patients who receive various preventive and therapeutic interventions, many patients do not receive them. This can be partially attributed to arbitrary diabetes management in hospital environments, which fail to attend to glycemic control. Failure to provide pro

In [4]:
from ucimlrepo import fetch_ucirepo

data = fetch_ucirepo(id=296)

df = data.data.features
target = data.data.targets


/usr/local/lib/python3.12/dist-packages/ucimlrepo/fetch.py:97: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)


In [5]:
df['readmitted'] = target


/tmp/ipython-input-772989973.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['readmitted'] = target


EDA Part 1

In [6]:
df.shape

(101766, 48)

In [7]:
df.head()

,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[0-10),NaN,6,25,1,1,NaN,Pediatrics-Endocrinology,...,No,No,No,No,No,No,No,No,No,NO
1,Caucasian,Female,[10-20),NaN,1,1,7,3,NaN,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,NaN,NaN,...,No,No,No,No,No,No,No,No,Yes,NO
3,Caucasian,Male,[30-40),NaN,1,1,7,2,NaN,NaN,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,Caucasian,Male,[40-50),NaN,1,1,7,1,NaN,NaN,...,No,Steady,No,No,No,No,No,Ch,Yes,NO


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   race                      99493 non-null   object
 1   gender                    101766 non-null  object
 2   age                       101766 non-null  object
 3   weight                    3197 non-null    object
 4   admission_type_id         101766 non-null  int64 
 5   discharge_disposition_id  101766 non-null  int64 
 6   admission_source_id       101766 non-null  int64 
 7   time_in_hospital          101766 non-null  int64 
 8   payer_code                61510 non-null   object
 9   medical_specialty         51817 non-null   object
 10  num_lab_procedures        101766 non-null  int64 
 11  num_procedures            101766 non-null  int64 
 12  num_medications           101766 non-null  int64 
 13  number_outpatient         101766 non-null  int64 
 14  numb

In [9]:
df.describe()

,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000


In [10]:
df.isnull().sum()

,0
race,2273
gender,0
age,0
weight,98569
admission_type_id,0
discharge_disposition_id,0
admission_source_id,0
time_in_hospital,0
payer_code,40256
medical_specialty,49949


Target Variable Analysis

In [11]:
df['readmitted'].value_counts()
df['readmitted'].value_counts(normalize=True)


,proportion
readmitted,
NO,0.539119
>30,0.349282
<30,0.111599


In [12]:
df['readmitted_binary'] = df['readmitted'].apply(lambda x: 1 if x == '<30' else 0)

df['readmitted_binary'].value_counts(normalize=True)


/tmp/ipython-input-2398817555.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['readmitted_binary'] = df['readmitted'].apply(lambda x: 1 if x == '<30' else 0)


,proportion
readmitted_binary,
0,0.888401
1,0.111599


In [13]:
df.loc[:, 'readmitted_binary'] = df['readmitted'].apply(lambda x: 1 if x == '<30' else 0)


Drop high-missing columns

In [14]:

df = df.drop(columns=[
    'weight',
    'payer_code',
    'medical_specialty',
    'max_glu_serum',
    'A1Cresult'
])


Drop IDs (no predictive value)

In [15]:
df = df.drop(columns=[
    'encounter_id',
    'patient_nbr'
], errors='ignore')


In [16]:
df.isnull().sum().sort_values(ascending=False).head(10)


,0
race,2273
diag_3,1423
diag_2,358
diag_1,21
discharge_disposition_id,0
admission_source_id,0
time_in_hospital,0
num_lab_procedures,0
num_procedures,0
gender,0


Handle Missing Values Properly

In [17]:
df['race'] = df['race'].fillna('Unknown')


In [18]:
df['diag_1'] = df['diag_1'].fillna('Unknown')
df['diag_2'] = df['diag_2'].fillna('Unknown')
df['diag_3'] = df['diag_3'].fillna('Unknown')


In [19]:
df.isnull().sum().sum()


np.int64(0)

FEATURE ENGINEERING

In [20]:
df['total_visits'] = (
    df['number_outpatient'] +
    df['number_emergency'] +
    df['number_inpatient']
)


Medication intensity

In [21]:
df['medication_intensity'] = df['num_medications']


Procedure intensity

In [22]:
df['procedure_intensity'] = df['num_procedures']


Lab intensity

In [23]:
df['lab_intensity'] = df['num_lab_procedures']


Exploratory Data Analysis

Age vs Readmission

In [24]:
df.groupby('age')['readmitted_binary'].mean().sort_index()


,readmitted_binary
age,
[0-10),0.018634
[10-20),0.057887
[20-30),0.142426
[30-40),0.112318
[40-50),0.106040
[50-60),0.096662
[60-70),0.111284
[70-80),0.117731
[80-90),0.120835


In [25]:

df.groupby('time_in_hospital')['readmitted_binary'].mean()


,readmitted_binary
time_in_hospital,
1,0.081785
2,0.099396
3,0.106668
4,0.118070
5,0.120309
6,0.125879
7,0.128350
8,0.142337
9,0.137242


In [26]:
df.groupby('total_visits')['readmitted_binary'].mean().head(20)


,readmitted_binary
total_visits,
0,0.081751
1,0.115641
2,0.146194
3,0.152778
4,0.171148
5,0.183694
6,0.232292
7,0.226959
8,0.245487


In [27]:
df.groupby('insulin')['readmitted_binary'].mean()


,readmitted_binary
insulin,
Down,0.138975
No,0.100374
Steady,0.111284
Up,0.129905


Patients not on insulin

Lowest readmission risk (~10%)

Likely milder diabetes cases

Dose change (Up / Down)

Higher risk (13–14%)

Indicates unstable glucose control

Steady insulin

Moderate risk

Managed but chronic condition

DATA PREPARATION FOR MODEL

In [28]:
df = df.drop(columns=['readmitted'])


Separate features (X) and target (y)

In [29]:
X = df.drop(columns=['readmitted_binary'])
y = df['readmitted_binary']


Convert categorical → numeric (Encoding)

In [30]:
import pandas as pd

X = pd.get_dummies(X, drop_first=True)


Check feature count

In [31]:
X.shape


(101766, 2334)

TRAIN TEST SPLIT

Split dataset

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


Check sizes

In [33]:
print(X_train.shape)
print(X_test.shape)


(81412, 2334)
(20354, 2334)


FIRST MODEL (Logistic Regression)

Train Logistic Regression

In [34]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

Predict

In [35]:
y_pred = model.predict(X_test)


Evaluate

In [36]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[18035    48]
 [ 2222    49]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     18083
           1       0.51      0.02      0.04      2271

    accuracy                           0.89     20354
   macro avg       0.70      0.51      0.49     20354
weighted avg       0.85      0.89      0.84     20354



Train Logistic Regression

In [37]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

Make predictions on test data

In [38]:
y_pred = model.predict(X_test)


Evaluate model

In [39]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[18035    48]
 [ 2222    49]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     18083
           1       0.51      0.02      0.04      2271

    accuracy                           0.89     20354
   macro avg       0.70      0.51      0.49     20354
weighted avg       0.85      0.89      0.84     20354



Train weighted logistic regression

In [41]:
from sklearn.linear_model import LogisticRegression

model_weighted = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'
)

model_weighted.fit(X_train, y_train)

y_pred_weighted = model_weighted.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred_weighted))
print(classification_report(y_test, y_pred_weighted))


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[11844  6239]
 [ 1026  1245]]
              precision    recall  f1-score   support

           0       0.92      0.65      0.77     18083
           1       0.17      0.55      0.26      2271

    accuracy                           0.64     20354
   macro avg       0.54      0.60      0.51     20354
weighted avg       0.84      0.64      0.71     20354



SMOTE

In [44]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)


In [45]:
y_train_smote.value_counts()


,count
readmitted_binary,
0,72326
1,72326


Train Random Forest on SMOTE Data

In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

rf_smote = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_smote.fit(X_train_smote, y_train_smote)

y_pred_rf_smote = rf_smote.predict(X_test)

print(confusion_matrix(y_test, y_pred_rf_smote))
print(classification_report(y_test, y_pred_rf_smote))


[[17953   130]
 [ 2207    64]]
              precision    recall  f1-score   support

           0       0.89      0.99      0.94     18083
           1       0.33      0.03      0.05      2271

    accuracy                           0.89     20354
   macro avg       0.61      0.51      0.50     20354
weighted avg       0.83      0.89      0.84     20354



In [47]:
 import pandas as pd

feature_importance = pd.Series(
    rf_smote.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

feature_importance.head(20)


,0
age_[50-60),0.029567
insulin_No,0.029274
age_[60-70),0.027263
lab_intensity,0.025625
num_lab_procedures,0.025620
age_[70-80),0.025363
insulin_Steady,0.024897
medication_intensity,0.023244
num_medications,0.023076
change_No,0.021522
